apiVersion: v1
entries:
  traefik:
    - apiVersion: v2
      appVersion: v3.6.15
      created: "2026-05-04T16:58:27.610015058-07:00"
      description: A custom Traefik based Kubernetes ingress controller
      digest: db6a7c4512a31a89163b2bb0a5a14155c44ad40926e7e9e670e61387382c1f99
      icon: https://raw.githubusercontent.com/traefik/traefik/master/docs/content/assets/img/traefik.logo.png
      kubeVersion: ">=1.25.0-0"
      maintainers:
        - email: test@test.com
          name: rthrall
      name: traefik
      type: application
      urls:
        - https://rthrall.github.io/raidho-traefik/traefik-39.0.5.tgz
      version: 39.0.5
generated: "2026-05-04T16:58:27.588288672-07:00"
